project: 
  type: website
  render:
    - "*.qmd"
    - "!admin/"
    - "!notes/"
  preview:
    port: 7777
    browser: false

metadata-files:
  - glossary.yml

website: 
  title: "CITF-Postdoc" 
  site-url: "https://zackbatist.info/CITF-Postdoc/" 
  repo-url: "https://github.com/zackbatist/CITF-Postdoc"
  repo-actions: [source]
  bread-crumbs: true
  page-navigation: false
  favicon: images/favicon.ico
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left:
      - text: "CC0"
        href: https://creativecommons.org/publicdomain/zero/1.0/

  sidebar:
    logo: "images/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: context.qmd
        text: Context
      - href: research-protocol.qmd
        text: Research Protocol
      - href: case-selection.qmd
        text: Case Selection
      - href: ethics-protocol.qmd
        text: Ethics Protocol
      - href: interview-protocol.qmd
        text: Interview Protocol
      - href: transcription-protocol.qmd
        text: Transcription Protocol
      - href: data-management.qmd
        text: Data Management
      - href: qda-protocol.qmd
        text: QDA Protocol
      - href: glossary.qmd
        text: Glossary
      - href: posts.qmd
        text: Blog
      - href: https://github.com/zackbatist/CITF-Postdoc
        text: GitHub
      - href: https://www.zotero.org/groups/5803066/citf-postdoc/library
        text: Zotero
      - href: posts.xml
        text: RSS

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - quarto
  - include-files.lua
  # - collect-citekeys.lua


execute:
  freeze: auto