project:
  type: website
  # pre-render: qc-atelier/shared/qc-pre-render.sh
  render:
    - "*.qmd"
    - "!private/"
    - "!data/CITF.qmd"
    - "!data/CITF.html"
    - "!data/CITF_files/"
    - "!data/*.excalidraw.png"
    - "!data/interviews/"
    - "!data/memos/"
    - "!qc/"
  preview:
    port: 7777
    browser: false
website:
  title: "CITF-Postdoc"
  site-url: "https://zackbatist.info/CITF-Postdoc/"
  repo-url: "https://github.com/zackbatist/CITF-Postdoc"
  repo-actions: [source]
  bread-crumbs: true
  page-navigation: false
  favicon: assets/resources/favicon.ico
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left:
      - text: "CC0"
        href: https://creativecommons.org/publicdomain/zero/1.0/
  sidebar:
    logo: "assets/resources/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: false
    collapse-level: 2
    contents:
      - index.qmd
      - research-protocol.qmd
      - section: "Supplementary"
        contents:
          - theoretical-framework.qmd
          - ethics-protocol.qmd
          - interview-protocol.qmd
          - data-management.qmd
          - qda-protocol.qmd
      - notes.qmd
      - posts.qmd
      - text: GitHub
        href: https://github.com/zackbatist/CITF-Postdoc
      - text: Bib
        href: assets/resources/CITF-Postdoc.bib
      - text: RSS
        href: posts.xml

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, assets/styles/theme-dark.scss]
    css: assets/styles/styles.css
    highlight-style: github
    include-in-header: assets/scripts/inline-code-interactions.html
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - quarto
  - assets/scripts/include-files.lua
  # - assets/scripts/collect-citekeys.lua

execute:
  freeze: auto

# resources:
  # - irb-docs.pdf