project: 
  type: website
  
website: 
  title: "CITF-Postdoc" 
  site-url: "https://zackbatist.info/MEDHI/" 
  repo-url: "https://github.com/zackbatist/MEDHI"
  repo-actions: [source]
  bread-crumbs: true
  page-navigation: false
  favicon: images/favicon.ico
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left:
      - text: "CC0"
        href: https://creativecommons.org/publicdomain/zero/1.0/

  sidebar:
    logo: "images/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: context.qmd
        text: Context
      - href: glossary.qmd
        text: Glossary
      - section: "Project Documentation"
        contents:
          - project-documentation/research-protocol.qmd
          - project-documentation/ethics-protocol.qmd
          - project-documentation/interview-protocol.qmd
          - project-documentation/coding-protocol.qmd
          - project-documentation/data-management.qmd
          - project-documentation/cases.qmd
      - posts.qmd
      - section: Resources
        contents:
          - href: https://github.com/zackbatist/CITF-Postdoc
            text: GitHub
          - href: https://www.zotero.org/groups/5803066/citf-postdoc/library
            text: Zotero
          - href: posts.xml
            text: RSS

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto
