project: 
  type: website
  render:
    - "*.qmd"
    - "!private/"
    - "!data/cases/"
    - "!data/interviews/"
    - "!data/memos/"
    - "!qc/"
  preview:
    port: 7777
    browser: false

website: 
  title: "CITF-Postdoc" 
  site-url: "https://zackbatist.info/CITF-Postdoc/" 
  repo-url: "https://github.com/zackbatist/CITF-Postdoc"
  repo-actions: [source]
  bread-crumbs: true
  page-navigation: false
  favicon: images/favicon.ico
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left:
      - text: "CC0"
        href: https://creativecommons.org/publicdomain/zero/1.0/
  sidebar:
    logo: "images/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: false
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: context.qmd
        text: Context
      - href: research-protocol.qmd
        text: Research Protocol
      - href: case-selection.qmd
        text: Case Selection
      - href: ethics-protocol.qmd
        text: Ethics Protocol
      - href: interview-protocol.qmd
        text: Interview Protocol
      - href: data-management.qmd
        text: Data Management
      - href: qda-protocol.qmd
        text: QDA Protocol
      - href: glossary.qmd
        text: Glossary
      - href: notes.qmd
        text: Notes
      - href: posts.qmd
        text: Blog
      - href: https://github.com/zackbatist/CITF-Postdoc
        text: GitHub
      - href: CITF-Postdoc.bib
        text: Bib
      - href: posts.xml
        text: RSS

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - quarto
  - include-files.lua
  # - collect-citekeys.lua

execute:
  freeze: auto

resources:
  - irb-docs.pdf