---
title: Cases
---
::: {.callout-note}
This document is still a work in progress.
:::

## Overview
In case-study research, cases represent discrete instances of a phenomenon that inform the researcher about it.
The cases are not the subjects of inquiry, and instead represent unique sets of circumstances that frame or contextualize the phenomenon of interest.
They must be selected with care, and in ways that serve the overall project's objective.
This document outlines the case selection strategy for this research.

## Case Study Research
Cases usually share common reference to the overall research themes, but exhibit variations that enable a researcher to capture different outlooks or perspectives on matters of common concern.
Drawing from multiple cases thus enables comprehensive coverage of a broad topic that no single case may cover on its own.

In other words, cases are contexts that ascribe particular local flavours to the activities I trace, and which I must consider to account fully for the range of motivations, circumstances and affordances that back decisions to perform activities and to implement them in specific ways.

Moreover, the power of case study research derives from identifying consistencies that relate cases to each other, while simultaneously highlighting how their unique and distinguishing facets contribute to their representativeness of the underlying phenomon.
Case study research therefore plays on the tensions that challenge relationships among cases and the phenomenon that they are being called upon to represent.

It should be noted that case study research limits my ability to derive generalized findings across the whole field of epidemiology.
As such, my intent is instead to articulate some significant aspects of data harmonization as they are represented at the cases accessible through this study.
In other words, I aim to make certain under-appreciated social and collaborative commitments that underlie data-sharing initiatives more visible and to draw greater attention to certain sensibilities, attitudes, and apprehensions that are relevant to contemporary discourse on the nature of epidemiological data and ongoing development of information infrastructures designed to support data integration and re-use.

## Comparative Factors
Comparison can be greatly facilitated if the bases for comparison are well thought out in advance.
Here I will identify factors that will enable me to draw comparisons among cases so that I may more effectively meet the project's objectives

To reiterate, this project investigates the social and collaborative apparatus that scaffold data harmonozation initiatives in epidemiology.
Through analysis of data obtained through interviews with various relevant stakeholders attached to data-sharing initiatives, the project will ascertain the actions taken and challenges experienced to mediate the varied motivations, needs and values of those involved.
In effect, the project aims to articulate the collaborative commitments that govern the constitution and maintenance of epidemiological information commons, and to relate these to technological, administrative and epistemic factors.

A few strands of thought come to mind:

- How close-knit is the web of projects that are sharing data?
  - Are they already very familiar with each other?
  - How were they recruited?
  - Do any participants seem "forced", or are they all a natural fit?

- How did data-sharing initiatives emerge?
  - Opportunistic? Problem-solving? Culmination of a long-standing desire? Accidental by-product?
  - How did these origins influence the social relations that came to shape the initiative?

- How are the commons governed?
  - What does the leadership look like, in terms of participants and their background, and the reasons for why they are in positions of power?
  - Is there a tier structure of community participation? What boundaries are being drawn, and why are they being drawn in the ways that they are?
  - What bounds the project as a whole?


## Fixed Cases
Maelstrom will serve as a “fixed point” that limits the scope of the cases’ breadth, while also ensuring that participants (and myself) have a common frame of reference.
This will greatly simplify the interviews by reducing the "overhead" of having to learn or be told about administrative or technical systems, which may distract from the core interest.

CITF will also serve as a fixed case.
This is for logistical issues, since the grant meant to support the CITF Databank.
But it is also so that the data can be compared with research on user experiences pertaining to CITF specifically, which will be performed concurrently with my own work.

## Limitations and Sources of Bias
- Identifying prospective interview participants, sampling
- Willingness to participate
- Prioritizing local connections and in-person interviews?


## Logistical Constraints
- 12 month time limit
- 12-15 interviews, 60-90 minutes in duration


@ragin1992

