---
title: Ethics Protocol
---
::: {.callout-note}
This document is still a work in progress.
:::

This page outlines my responses to questions from McGill University's Institutional Review Board.
Although my project is covered by the most recent CITF grant and I will not be submitting these responses for review, I still consider it important to address these concerns here in writing as a matter of research integrity.

## Recruitment and consent
**How are potential study participants identified and/or recruited to the study?**
Explain how potential participants are identified or introduced to the study, and who will recruit participants. Will the investigator/s require any special permissions or access to the target population e.g. clinic access, patient registries or records, mailing lists, community access?

Through consultation with key community stakeholders, I will devise a list of prospective projects to serve as cases (see the [case selection protocol](case-selection.qmd) for further details).
I will then write to the leaders of these projects inviting them to participate in my research.
These invitations to project leaders will eplain who I am, what the study is about, and why I am doing it, and will encourage the recipient to reply with any questions or concerns they may have.
If they accept the invitation, I will then work with project leaders to devise a list of individuals who may serve as valubale interview candidates based on their roles in the project.
I will be clear with project leaders that they should not pressure those who work for them to participate in my research, and that individuals' participation should be treated as separate from their regular duties; if they can not or will not abide by this condition, their project will be rejected as a prospective case.
I will then write to the recommended individuals to introduce the study and its objectives and to invite them to participate as research subjects.

**Describe the consent process.**
If alternate processes for seeking consent are planned (e.g. verbal, online, waiver), please provide a rationale and outline the procedure of obtaining and documenting consent and/or assent, where applicable.

Once individuals express their interest in participating, I will provide them with an [informed consent document]() that outlines in more detail the goals of the study, the roles of the participant, how they will be recorded, how data pertaining to them will be retained, and the potential risks and benefits pertaining to their involvement.
This document will also describe how their personally identifiable information will be managed and used.
Participants will be asked to read and sign the document in order to obtain written informed consent.
At the start of each interview I will reiterate participants' rights and ask them to orally reaffirm their consent before proceeding.

**Is there a relationship between the study participants and the person obtaining consent and/or the principal investigator/s?**
If yes, please explain the nature of the relationship, and outline the steps that will be taken to avoid the perception of undue influence.

One project that serves as a case in this research is the Covid-19 Immunity Task Force (CITF), which I currently serve as postdoctoral researcher.
Some of the participants will therefore be colleagues; the interviews will remain structured and limited in scope, and will not touch on matters relating to other aspects of our work.

I will consult with Dr. David Buckeridge, who leads the CITF, as a key community stakeholder to help devise a shortlist of projects that may serve as prospective cases.

## Risk-benefit assessment
**Describe the foreseeable risks to study participants.**
What risks are attributable to the research, including cumulative risks? Which risks are participants normally exposed to in the course of their clinical care or in their daily activities as they relate to the research questions/objectives?

Participation in this research project does not involve any physical, psychological or legal risks.
However, I will be asking participants to share detailed information about their work practices and work relationships, and public association with their responses may potentially disrupt or complicate their professional reputations.
To mitigate against this potential harm, I will give participants the option to render their responses confidential.

**What procedures are in place to monitor and assess participant safety for the duration of the study?**

Prior to each interview, and as part of the procedure for obtaining informed consent, I will ask participants about whether they want to render their responses confidential.
Immediately after each interview, I will give participants an opportunity to reflect on their responses and reiterate the option to render their prior responses confidential.
Furthermore, for participants who have not requested that their responses be treated as confidential immediately before and after the interview, I will follow up one week after the interview to reiterate the option; I will wait one additional week for them to inform me if they decide to keep their responses confidential before continuing to process, transcribe and analyze their interviews.

**Describe the potential benefits of the study for:**
(1) the study participants; (2) the population under investigation, and (3) the field of research.

This study contributes to the development of better epidemiological data-sharing infrastructures by articulating social, collaborative and discursive aspects of data-sharing, and how these factors relate to, overlap with or conflict with technical, institutional and epistemic factors.
By explicitly framing data-sharing as a social and collaborative activity, epidemiological datasets shared through open data infrastructures can be more effectively contextualized and rendered more usable for research.
This work therefore poses new ways to document how epidemiologists mobilize distributed records in the constitution of synthetic knowledge, and helps develop practical solutions that enable greater reflexivity.

This work will enable participants to improve professional practice by being more aware and reflexive of their research practices as a result of the questions that are raised during interviews and observations, which frame their work in ways that they may not have otherwise considered.

## Privacy and confidentiality
**Please describe the measures in place for meeting confidentiality obligations.**
How is information and data safeguarded for the full cycle of the study: i.e. during its collection, use, dissemination, retention, and/or disposal?

The specific circumstances that frame each case are significant factors that will shape my findings, and the study will benefit from participants consenting to associate their identities with their interview responses.
Nevertheless, I will provide participants with the option to render teir interview responses confidential.

I acknowledge that I am engaging with a relatively small research community and that there is minimal social risk that others may be able to determine the identities of those whose research practices and professional relationships are being documented, even if I render their responses confidential.
To address this issue, I will ensure that if any single participant from a case decides to render their responses confidential, I will render the responses of all participants pertaining to that case condidential as well, and shield the identify of the project that serves as the case too.

I will adhere to fundamental data security practices throughout the entire project.
This will include storing all data, including backups, in encrypted drives, and keeping all physical records and digital storage drives in locked drawers or cabinets when not in use or when left unsupervised.
Moreover, I will adhere to [McGill University's Cloud Directive](https://www.mcgill.ca/cloud-directive).
See the [data management plan](data-management.qmd) for further details on how information pertaining to this project will be collected, curated and shared.

**If a contracted cloud/storage service provider or online survey tool is used,** provide information on the service provider's security and privacy policy, location of its servers, data ownership, and what happens to the stored data after the contract is terminated. For more information, please consult the University's directive.

I will use [McGill University's OneDrive service / the CITF SharePoint instance] to backup all files maintained for this study.
These backups will include files containing information that might reveal participants' identities.
This service is managed by McGill University and has been approved for storing sensitive research data by the [Cloud Directive](https://www.mcgill.ca/cloud-directive).

I may use MaxQDA's TeamCloud service, which facilitates collaborative use of their software, and MaxQDA's AI Assist service, which enhances data processing workflows and analytic procedures.
MaxQDA adheres to [strict data retention and security policies](https://help.maxqda.com/en/support/solutions/articles/80001135288-what-about-data-security-and-data-privacy-of-ai-assist-) for all its cloud services; it relies on GDPR-compliant Amazon Bedrock servers, which are widely regarded as the most secure commercially-available cloud instrastructure.
I am currently drafting a request for institutional approval of these services under McGill University's Cloud Directive.

I maintain a website where I share documentation that supports this project and reflect on the work as it progresses.
This is hosted using GitHub Pages and is backed up using Dropbox.
The website exists to document my research practices, and no sensitive research data will pass through these services.

**Please explain any reasonable and foreseeable disclosure requirements**
(e.g. disclosure to third parties such as government agencies or departments, community partners in research, personnel from an agency that monitors research, research sponsor, the REB/IRB, or regulatory agencies).

**If there are plans for retaining participant and/or study data for future use,** please describe the context for its use, requirements for potentially re-contacting study participants and consent, and how the data will be stored and maintained for the long term.

I will publish research data in compliance with ethical standards for sharing open social science research data.
I will not share audio and video recordings of interviews, nor will I share unedited transcripts that retain personally-identifying information pertaining to participants who have requested that their responses be rendered confidential.
I will publish the database containing codings, memos and trends deriving from qualitative data analysis, which will be scrubbed of all personally-identifying information pertaining to participants who have requested that their responses be rendered confidential.

I may request that study participants sit for an additional interview in case I am unable to gather the information I set out to obtain from them during the time we initially agree to meet.
I will reiterate my request for informed consent prior to each interview.

I may follow up with the leaders of the data-sharing initiatives that serve as cases for this project to share the results with them and to present them with constructive feedback deriving from my findings.
I may also invite them to collaborate on a position paper advocating for reforms based on the project's findings.

**Secondary use of data studies:**
if the study involves data linkage, please describe the data that will be linked and the likelihood that identifiable information will be created through the linkage.

This project does not rely on data deriving from other studies.
The data may be reused in related work being undertaken under the same grant and by those who access the openly accessible data after they are published.

## Managing conflicts of interest
Conflicts of interest do not imply wrong-doing. It is the responsibility of the investigator to determine if any conflicts apply to any person/s involved in the design and/or conduct of the research study or any member of their immediate family. Disclose all contracts and any conflicts of interest (real, perceived, or potential) relating to this research project. Conflict of interest may also arise with regard to the disclosure of personal health information.

- [x] Not applicable. There are no conflicts of interest to disclose.
- [ ] Yes, there are conflicts of interest to disclose.

**If yes, please describe the conflicts of interest (real, potential, and perceived), and the procedures for managing declared conflicts.** Not applicable.
