---
title: Interview Protocol
---

# Interview records
Interviews may be held either in-person or through online video conference.
All interviews will be held in quiet and comfortable environments, such as office spaces or conference rooms.

I will record all in-person interviews using a SONY ICD-UX560 audio recorder to capture audio in the lossless 16 bit 44.1 kHz Linear PCM wav format, with additional audio filters to enhance playback during transcription, if necessary.

I will also record in-person interview sessions using a GoPro Hero 4 Silver action camera, depending on participants willingness to be video recorded.
Based on prior interviews with scientists about their research experiences, I found that interviewees like to show me, rather than merely tell me, about what they are working on and the means through which they engage with information systems.
The camera may be leveraged to record spontaneous video records of these demonstrations and provide me with an additional rich data source for further analysis.
Moreover, the camera provides an additional backup audio recording in case of data loss on the primary recording device.

Remote interviews will be recorded using the video conferencing software's built-in recording tools.
Participants will be instructed to disable their microphones or video cameras prior to initiating recording if they have opted to not be recorded through these media.
I will record all media locally and refrain from using any cloud services to store or modify the records which the video conference software may provide.

I will also record handwritten or typed notes comprising descriptive accounts of activities and interactions when recording devices are switched off, as well as preliminary interpretations of observed behaviours and notes on things I plan to follow up on at a later time.

All records, including audio and video records, notes, transcripts, interview guides and planning documents are kept confidential until consent has been granted to release materials relating to participants' responses.

# Interview guide
Interviews will be semi-structured, following a broad pattern of inquiry, though the specific questions may vary.
In keeping with my methodological preference toward highlighting situated attitudes and experiences [cf. @knorrcetina2001; @suchman2007; @clarke2016], interviews will trace (1) participants' goals and perspectives; (2) their projects' missions, purposes and motivations; and (3) the practices, procedures and relationships that enable them to operationalize their personal and collective goals.
This approach allows me to examine how participants relate their own identities and experiences to communities' collective interests (in terms of affinities, aversions, or other associations) and reflect on their capacity to act individually and in concert with others.
More specifically, participants will be asked to reflect on:

- the motivations for their initiatives;
- the challenges they experience;
- how they envision success and failure;
- their perceptions of their own roles and the roles of other team members and stakeholders;
- the values that inform their decisions;
- how the technological apparatus they set up enables them to realize their goals and values; and
- ways in which they believe data-sharing could be improved.

The questions will be tailored to each individual interviewee so that they may address their responses in general terms and in relation to their own specific experiences.
With this in mind, each interview will proceed following a strategic order:

## 1. Participants' goals and perspectives
Follow a life-history method to better understand participants' professional backgrounds and their roles within their projects.
The goal is to obtain information about their paths, not the rehearsed origin story.

- To start, can you please tell me a little bit about your background?
- What is the project, and what is your role?
- How did you find yourself in this role?
- How has your previous experience prepared you for your role?

## 2. Projects' missions, purposes, motivations
This section is about the project in general, including its purpose, scope and value.
Information about practices and procedures will be sought in a subsequent phase of the interview.

- What are the project's goals?
- What makes the project unique?
- What is the project doing that no other similar project is doing?
- Do you consider this project as similar to any other initiatives?
- What are they, and in what ways are they similar or different?

[]()

- What are the expected outcomes?
- Have you achieved these goals and outcomes?
- If not, are you on track to achieving them?
- What are some challenges that the project experienced, and how have you worked to overcome them?

## 3. Practices, procedures, relationships
This section asks about specific actions and interactions that the participant engages in.

### Roles and relationships
- What does your role entail?
- Can you provide a couple examples of things that you recently did in this capacity?

[]()

- Who else do you frequently rely on, and what are their roles?
- Can you describe what they do, and perhaps give a few examples drawn from their recent work?

The interview might proceed in different ways depending on their initial responses.
Here are some questions I might ask, corresponding with the participants' role and area of expertise.

### Maintaining the project community
- Please briefly describe the process through which you obtain new partners or users.
- Can you please recall a recent example?

[]()

- How well do you know each partner?
- Did you know them before their involvement?

[]()

- Would you describe the project as a tight knit community, or more open-ended?

[]()

- How do you communicate with partners and contributors?
- What kinds of media or platforms do you use, and are they targeted for specific purposes? i.e. email, newsletters, social media, skype, personal communication at conferences

[]()

- Are there particular people in each project who you communicate with more frequently than others?
- Who are they, and why are these the people who you connect with?

[]()

- What do you consider your role or responsibility vis-a-vis the development/growth of this community?
- How do you foster the community's development and growth?
- Do you consider these efforts to be effective?

[]()

- Does your role as someone who leads a data harmonization initiative differentiate you from other epidemiologists?
- How has your relationship with other epidemiologists changed after initiating this project and taking on this role?

### Reflections on data's value
- How has the data been used or analyzed?
- Do you track how the data is used?
- Is this tracking formal or informal?

[]()

- What patterns or trends are apparent based on this tracking?
- In your view, has the data been used in productive ways?
- In what ways are people either maximizing or not fully utilizing the data's full potential?

[]()

- Can you tell me about any unexpected or alternative uses of the data?
- What made them significant to you?

[]()

- Which skills and competencies do you think researchers need to possess in order to be able to make proper use of the data in their work?

[]()

- Based on your experience, what are the main obstacles for the effective and widespread adoption of these skills?
- What are some positive factors, or drivers, that can make that prospect more tangible?

### Data ownership
- Who has rights (in the legal sense or informally) over the information contained in the system, or in related documents and datasets?
- Can you tell me about any conflicts or tensions that emerged relating to expressions of propriety or ownership over data?

### Collecting data
- Do projects collect data with future harmonization in mind?
- If so, how does this affect data collection procedures, and does this play a role in subsequent decision-making?

### Curating data
- Please describe the overall process of getting data into the system and then working with the data.

[]()

- Please tell me about any unexpected or problematic cases that made working with data particularly challenging.
- What made these cases unique or challenging?
- How did you resolve them or work towards a solution or viable outcome?

### Accessing data
- Do you consider the system easy to access?
- Can you identify some challenges that pose as barriers to access?

[]()

- Who has access to data?
- How are decisions regarding access rights made?
- Can you tell me about any unnaceptable practices regarding accessing and sharing data?

### Using data
- If you engage with the data with specific questions in mind, how do these questions emerge?
- What role does the data play in shaping the questions and analytical approach?

[]()

- Is the system amenable to exploratory or serendipitous modes of discovery?
- Please tell me about specific examples where you engaged with the data in this way.

[]()

- What features does the system have to view or export data?
- How easy is it to view, export or visualize data the data?
- Do you use the tools that are designed to export of visualize data, or do you prefer to use your own tooling?
- What are the reasons behind this preference?

### Documentation
- How is the system documented?
- Who is responsible for creating documentation?
- Can you please tell me about a great example of documentation in your project?

[]()

- Overall, do you consider your project's documentation to be helpful?
- Why or why not?

[]()

- In your opinion, does the documentation accurately reflect the true nature of the documented data or work practices?
- Are specific things more accurately documented than others?
- Please tell me why you think some things are more accurately or less accurately documented.

[]()

- Can you recall any instances when documentation was updated?
- What prompted these updates?

[]()

- Do people ever get in touch to ask questions about specific aspects of the data or data curation procedures?
- What kinds of questions do they ask?
- What kinds of responses are given?

### Relationships with Maelstrom
- Can you please concisely describe the role of Maelstrom as part of your project's overall initiative?

[]()

- What are the origins of your project's relationship with Maelstrom?
- How has this relationship changed over time?

[]()

- Does your project present any unique challenges or require any special attention?
- If so, please tell me about some unique cases or examples that demonstrate this unique relationship.

[]()

- Do you believe that Maelstrom is meeting your project's needs and enabling it to achieve its goals?
- In what ways is Maelstrom either satisfying or failing to meet your project's expectations or needs?
- How would you change the current system to better suit your project's needs more effectively?

[]()

- Do you engage with Maelstrom's other partners?
- If so, what is the nature of these relationships?

# General Tips and Strategies
Here are some potentially helpful prompts to keep the conversation flowing:

- What happened next?
- Who was that person?
- Tell me more about that development or event.
- Please give me an example.
- Do you remember a specific time when you did this?

