---
title: "Postdoc-Main Manuscript"
date: today
bibliography: references.bib
authors:
  - name: Zachary Batist
    id: zb
    email: zachary.batist@mcgill.ca
    url: https://zackbatist.info
    orcid: 0000-0003-0435-508X
    affiliations:
      - name: McGill University
        department: Epidemiology, Biostatistics and Occupational Health
        city: Montreal
        region: Québec
        country: Canada
abstract: |
  Blah.
keywords:
  - research data sharing
  - data governance
citation:
  type: article-journal
  url: https://zackbatist.info/CITF-Postdoc/
  abstract: ""
filters: 
  - ../assets/scripts/count-para.lua
format:
  html:
    number-sections: false
#   pdf:
#     documentclass: article
#     geometry:
#       - top = 1in
#       - bottom = 1in
#       - left = 1in
#       - right = 1in
#     colorlinks: true
#     toc: false
#     include-in-header:
#       text: |
#         \usepackage{orcidlink}
#         \usepackage{marvosym}
#     template-partials:
#       - ../assets/styles/title.tex
# format-links: 
#   - pdf
#   - text: GitHub
#     icon: github
#     href: https://github.com/zackbatist/CITF-Postdoc
---

```{css, echo = FALSE}
p {
  text-align: justify !important;
}
```


<!-- ```{r setup}

```

```{r dependencies}

```

```{r plot-theme}

``` -->

{{< include sections/01_background.qmd >}}
{{< include sections/02_methods.qmd >}}
{{< include sections/03_results.qmd >}}
{{< include sections/04_discussion.qmd >}}
{{< include sections/05_conclusions.qmd >}}
{{< include sections/10_references.qmd >}}
{{< include sections/11_back-matter.qmd >}}
<!-- {{< include sections/12_supplement.qmd >}} -->
