---
title: "Cases"
author:
  - name: "Zack Batist"
  - orcid: 0000-0003-0435-508X
  - email: zacharybatist@gmail.com
bibliography: /Users/zackbatist/Library/CloudStorage/Dropbox/zotero/zack.bib
toc-title: ""
toc-depth: 3
toc-expand: 3
# license: "CC0"
---

## Overview
In case-study research, cases represent discrete instances of a phenomenon that inform the researcher about it.
Cases are selected based on their relevance to a central topic and their ability to contribute novel insights about it [@ragin1992].
Cases usually share common reference to the overall research themes, but exhibit variations that enable a researcher to capture different outlooks or perspectives on the matter of communal interest.
Drawing from multiple cases thus enables comprehensive coverage of a broad topic that no single case may cover on its own.

The cases are not the subjects of inquiry.
Instead, they represent unique sets of circumstances that frame or contextualize the phenomenon of interest.
Using grounded theory, I will draw out the common and patterned themes that cut across cases, while simultaneously reflecting on the unique circumstances that differentiate them.
In other words, cases are contexts that ascribe particular local flavours to the activities I trace, and which I must consider to account fully for the range of motivations, circumstances and affordances that back decisions to perform activities and to implement them in specific ways.

This follows the approach advocated that Nicolini (2009) and Maryl et al. (2020: para. 30) advocate. They suggest “zooming
in to a granular study of particular research activities and operations and zooming out to considering broader socio-technical and cultural factors”.
This involves “magnifying or blowing up the details of practice, switching theoretical lenses, and selective re-positioning so that certain aspects are fore-grounded and others are temporarily sent to the background” (Nicolini 2009: 1412).
This approach is useful for me because data-sharing initiatives all start from different positions but share common practices and tendencies that vary according to those contextual circumstances.
Thus I can tactfully switch between those lenses to understand the interplay between circumstances and practical implementations.

However, comparison can be facilitated if the basis for comparison is well thought out in advance.
Here I will identify factors that will enable me to draw comparisons among cases so that I may more effectively meet the project's objectives

## Reiteration of Goals
The goal of this project is to...

The research questions are...

## Comparative Factors
Maelstrom will serve as a “fixed point” that limits the scope of the cases’ breadth, while also ensuring that participants (and myself) have a common frame of reference.
This will greatly simplify the interviews by reducing the "overhead" of having to learn or be told about administrative or technical systems, which may distract from the core interest.

CITF will also serve as a fixed case.
This is for logistical issues, since the grant meant to support the CITF Databank.
But it is also so that the data can be compared with research on user experiences pertaining to CITF specifically, which will be performed concurrently with my own work.

## Limitations and Sources of Bias
- Identifying prospective interview participants, sampling
- Willingness to participate
- Prioritizing local connections and in-person interviews?


## Logistical Constraints
- 12 month time limit
- 12-15 interviews, 60-90 minutes in duration




