---
title: Coding methods
description: Notes perpainting to coding methods that may be useful for this project.
date: 2025-02-25
date-modified: last-modified
toc-depth: 6
toc-expand: 3
reference-location: document
categories: 
  - QDA methods
  - coding
  - reading
---

Some notes on coding methods that stand out as relevant to my work.
Largely drawn from Saldaña's [-@saldana2016] excellent coding manual.

These notes should be treated as relating to my research specifically, and should not be considered generalizable.
They are more like my impressions of their practical value for my own purposes.
I therefore priorize notes on methods that I deem especially relevant to my research.

# First cycle coding methods
## Grammatical methods
Refer to the basic grammatical principles of a technique, by articulating the forms and combinations of codes and encoded elements in a dataset.

### Attribute coding
- Could be useful for identifying affiliations or former affiliations, including who is or was their doctoral supervisor, whether they are a student, research associate or faculty member, etc.
- But I imagine this might be better represented in a memo outlining a "cast of characters" rather than as codings.

### Magnitude coding
- Can be applied to tag positive/negative attitudes, but also other gradients like hard/soft, technical/social skills.
- Can use colons to identify a magnitude facet for specific codes corresponding with the code's usage in the specific context.
  - For example: using `programming: 1` or `programming: 5` to identify different instances of programming and the degree of difficulty elicited regarding each instance.
  - See additional examples at Saldaña [-@saldana2016: 88-19].

### Subcoding

### Simultaneous coding

## Elemental methods
Basic but focused filters for reviewing the corpus, which build a foundation for future coding cycles.

### Structural coding
- Useful for identifying components of an interview transcript that may not matter as much, such as interviewer questions, long pauses or interuptions, or standardized preambles.

### Descriptive coding
- I should minimize this kind of coding, and replace with "initial / open" coding, use of sensitizing concepts, or in vivo coding instead.
- Speaking of sensitizing concepts, I could use the prefix `SC:` to denote these as a distinct kind of code.
- Saldaña likens them to hashtags on social media.

### In vivo coding
- I imagine creating in vivo codes in an opportunistic way, whenever I see something that really stands out, and therefore is best applied during an initial or open pass through the document.
- For this reason, I should distinguish these codes with a prefix `IV:`.
- I imagime this could be especially useful to articulate the improvised adoption of certain terms or imagery, which can be somewhat haphazard (as per my observation that the curatorial lens reifies and perpetuates certain notions of data based on common and/or authoritative use of specific terms across contexts).

### Process coding
- This one will be very important, I think.
- Essentially entails framing ordinary things in terms of broader improvised actions, as attempts, as interactions between people and between agents.
- Saldaña suggests embodying these codes through gestures, even while coding, as an arts-based heuristic.

From Clarke [-@clarke2003: 558] on process coding:

> In a traditional grounded theory study, the key or basic social process is typically articulated in gerund form connoting ongoing action at an abstract level.
> Around this basic process are then constellated the particular and distinctive conditions, strategies, actions, and practices engaged in by human and nonhuman actors in volved with/in the process and their consequences.
> For example, subprocesses of disciplining the scientific study of reproduction include formalizing a scientific discipline, gleaning fiscal support for research, producing contraceptives and other techno scientific products, and handling any social controversies the science provokes (such as cloning and stem cell research).

### Initial coding
- Also referred to as "open coding".
- Breaks down data into discrete parts, closely examines the, and compares for similarities and differences.
- Important to remain open to all possible theoretical directions suggested by your interpretations of the data.
- An opportunity to reflect deeply on the contents and nuances of the data and to begin taking ownership over them.
- @charmaz2014 suggests doing this line-by-line over each document as they are ingested into the dataset.

### Concept coding
- What Saldaña refers to as "concept coding" is what I have previously referred to as "theoretical coding", to a certain extent.
- It's a form of lumping, identifying specific instances under the label of cohesive concepts.

## Affective methods
Investigate the subjective qualities of human experience (including emotions, values, conflicts and judgements) by directly acknowledging and naming those experiences.
These affective qualities are core motives for human action, reaction and interaction.

### Emotion coding
- Distinguishes between emotions and moods:
  - **Emotion:** a feeling and its distinctive thoughts, psychological and biological states, and range of propensities to act.
  - **Mood:** a general aura, sustained quality, or the perception of another's emotional tone.
- Mood may be more relevant to me, especially when identifying aspects of phases or contexts of work.

### Values coding
- Actually entails coding values, attitudes and bliefs:
  - A **value** is the importance we attribute to ourselves, another person, thing, or idea; the principles, moral codes, and situational norms people live by.
  - An **attitude** is the way we think and feel about ourselves, another person, thing or idea, and are part of a relatively enduring system of evaluative, affective reactions.
  - A **belief** is part of a system that includes our values and attitudes, plus our personal knowledge, experiences, opinions, prejudices, morals, and other perceptions of the social world; they can be considered as "rules for action".
- Use prefixes `V:`, `A:` and `B:` to distinguish these things.
- Some key phrases that signpost values, attitudes and beliefs include:
  - It's important that...
  - I like...
  - I love...
  - I need...
  - I think...
  - I feel...
  - I want...

### Versus coding
- Identifies in dichotomous or binary terms the individuals, groups, social systems, organizations, phenomena, processes, concepts, etc in direct conflict with each other.
- These moities generally exhibit power imbalances.
- Saldaña does not specify this, but the framing of a duality also draws an association as things that may be compared along opposite ends of the same spectrum; this gives them something in common, and figuring out that commonality that exists alongside the differences could be really insightful, perhaps.
- Saldaña advises against getting too caught up in the hero/villain, protagonist/antogist dichotomy, and reminds us that these dualities are context-specific and should be treated as such.

### Evaluation coding
- Commonly used in situations where participants are asked to assign judgements to the merit, worth, or significance of programs or policy.
- Evaluation data may describe, compare or predict:
  - **Description** focuses on patterned observations or participant responses of attributes that assess their quality.
  - **Comparison** explores how the program measures up to a standard or ideal.
  - **Prediction** provides recommendations for change, if needed, and how those changes^[Saldaña [-@saldana2016: 144] notes that "change" is a slippery and contested term, and suggests using more precise terms like "impact", "shift", "transformation" andn"evolution" instead. This is just solid advice that applies in other contexts too.] might be implemented.

## Literary and language methods
Borrow from established approaches in the analysis of literature and oral communication to explore underlying sociological, psychological and cultural constructs.

### Dramaturgical coding
- Approaches naturalistic observations and interview narratives as "social drama".
- Life is perceived as performance, with humans cast as characters in conflict.
- Interview transcripts are framed as dialogue, soliloquy and dialogue; field notes and naturalistic videos are framed as improvized scenarious with stage direction.
- Environments, dress and artefacts are viewed as scenery, costumes and props.
- This is enacted by applying terms and conventions from scriptwriting as code prefixes:
  - `OBJ`: participant-actor objectives
  - `CON`: conflicts or obstacles
  - `TAC`: tactics or strategies to deal with conflucts
  - `ATT`: attitudes toward setting, others, or conflicts
  - `EMO`: emotions experiences by actors
  - `SUB`: subtexts, or the actors' unspoken thought or impression management
- Useful in projects leading to narrative or arts-based presentational forms.
- Also useful to trace daily routines or regular interactions among participants.
- Best applied to self-standing, inclusive vignettes, episodes or stories in the data record, which may even be divided into stanzas or scenes connected  by plotting devies like curtain-raising or prologues.

### Motif coding
- Used to classify types and elements of folk tales, myths and legends.
- A motif as a literary device is an element that sometimes appears several times within a narrative work.
- A _type_ refers to the complete tale, whereas a _motif_ refers to the smallest element in a tale that has something unique about it, such as kinds of characters, significant objects, and/or incidents of action.
- Appropriate for exploring identity studies and oral histories.

### Narrative coding
- Identifies elements of narrative and story-telling, such as conflict, flashback/flashforward, vignette, resolution, aside, subtext, etc.
- Suitable for inquiries on identity development, psychological, social and cultural meanings and values, critical/feminist studies, and documentation of the life course.

### Verbal exchange coding
- Entails verbatim transcript analysis and interpretation of the types of conversation and personal meanings of key moments in the exchanges.
- Coding determines the "generic type" of conversation, and reflection examines the meaning of the conversation.
- Some generic types of conversation include: phatic communication or ritual interaction; ordinary conversation; skilled conversation; personal narratives; and dialogue.
- After classifying conversations, the analyst explores personal meanings and key moments by examining speech mannerisms, non-verbal communication habits and rich points of cultural knowledge (slang, jargon, etc).
- This them proceeds to examine the practices or cultural performances evident in these interactions, which are situated on a continuum:
  1. routines and rituals of structured, symbolically meaningful actions during our day
  2. surprise-and-sense0making episodes of the unanticipated or unexpected
  3. rosl-taking episodes and face-saving episodes of conflict-laden exchanges
  4. crises in a verbal exchange or as an overarching pattern of lived experience
  5. rites of passage, or what is done that significantly alters or changes our personal sense of self or out social or professional status or identity
- Useul for examining dialogical interaction.

## Exploratory methods
Exploratory and preliminary assignments of coces to the data before more refined coding systems are developed and applied.

### Holistic coding
- Attempts to grasp basic themes or issues in the data by absorbing them as a whole (by lumping them) rather than by analyzing them line by line (by splitting).
- This is a preparatory approach to a unit of data before a more detailed coding or categorization process occurs.
- I imagine this as being somewhat similar to open/initial coding, but operating at a coarser grain.
- Useful for "chunking" the data into broader topics as a preliminary step for more detailed analysis.
- Could also be a time-saving method if there is a massive amount of data.

### Provisional coding
- Establishes a predetermined list of codes prior to fieldwork, developed from anticipated categories or types of responses or actions that may arise in the data yet to be collected.
- The provisional list is generated through literature reviews, the study's conceptual framework and research questions, previous findings, pilot study fieldwork, the researcher's prior knowledge and experiences, and researcher-formulated hypotheses or hunches.
- As data are collected, coded and analyzed, provisional codes can be revised, modified, deleted or expanded.
- Useful in research that builds on or seeks to corroborate previous investigations.
- May make use of keyword searches to locate terms and phrases that may correspond with the provisional codes.

### Hypothesis coding
- The application of a researcher-generated, predetermined list of codes specifically to assess a researcher's hypothesis.
- The codes are developed from a theory or prediction about what will be found in the data before they have been collected or analyzed.
- Particularly useful if seeking to identify rules, causes and explanations.
- Can also be applied midway or later in the analysis process to confirm or disconfirm any assertions or theories made thus far.

## Procedural methods
Comprise pre-established coding systems or very specific ways of analyzing qualitative data.

### Protocol coding
- Also referred to as "a priori coding".
- A protocol is a detailed and specific set of procedural guidelines for conducting an experiment, administering a treatment or conducting field research and data analysis.
- A predefined list of codes and categories is provided to the researher and applied to the data after collection.
- The defitions of all codes should be clear and inclusive of all possible types of responses to be collected.
- Could be useful when examining video-recorded data and focus group transcripts, especially in contexts with multiple coders.

### Outline of cultural materials coding
- A topical index for anthropologists and archaeologists, providing coding for the categories of social life that have traditionally been included in ethnographic description.
- Serves to organize the database of the Human Relations Area Files (HLAF), which is a massive collection of ethnographic field notes about hundreds of world cultures collected over the past several decades.
- May be especially useful for indexing, rather than coding, field notes.

### Domain and taxonomic coding
- A method for discovering the cultural knowledge people use to organize their behaviours and organize their experiences.
- We call categories that categorize other categires _domains_, and the words that name them _cover terms_.
- Taxonomies are hierarchical lists of different things that are classified together under a domain word on the basis of some shared attributes.
- Better to apply terms used by informants (referred to as _folk terms_) but when no term is offered then researchers may apply _analytic terms_.
- Nine possible semantic relationships exist within domains (and which relate the items in the nested hierarchy):
  - **Strict inclusion:** X is a kind of Y
  - **Spatial:** X is a place in or a part of Y
  - **Cause-effect:** X is a result or cause of Y
  - **Rationale:** X is a reason for doing Y
  - **Location for action:** X is a place for doing Y
  - **Function:** X is used for Y
  - **Means-end:** X is a way to do Y
  - **Sequence:** X is a step in Y
  - **Attribution:** X is an an attribute of Y
- Strict inclusion forms are generally nounce, and means-end forms are generally verbs.
- For analysis, a semantic relationship is chosen, and the data are then reviewed to find examples of the semantic relationship.
- Related forms and analytical terms are noted, and a _folk taxonomy_ emerges as a set of categories organized on the basis of a single semantic relationship.

### Causation coding
- Locates, extracts and/or infers causal beliefs.
- Attempts to label the mental models participants use to uncover what people believe about events and their causes.
- An attribution is an expression of the way a person things about the relationship between a cause and an outcome, and can consist of an event, action or characteristic.
- It is important to remain focused on the individual who performs the action, rather than variables pertaining to the individual such as social class, sex, ethnicity, etc.

# Themeing the data
- A theme is an outcome of coding, categorization and analytic reflection, not something that is itself coded.
- However it could also be useful to label portions of the data with extended thematic statements rather than codes.
- A theme is an extended phrase of sentence that identifies what a unit of data is _about_ and/or what it _means_.
- They are discerned during data collection and initial analysis.
- The analytic goal is to winnow down the number of themes to explore in a report and to develop an overarching theme from the data corpus or an integrative theme that weaves various themes together into a coherent narrative.
- Themes may be identified at the manifesr level (directly observable) or at the latent level (underlying the observed phenomenon).
- At the manifest level, a theme functions as a way to categorize a set of data into an implicit topic that organizes a group of repeating ideas.
- This foundation work leads to the development of higher-level theoretical constructs when similar themes are clustered together.
- At the latent level, themes serve phenemenology, which is driven my an objective of gaining a deeper understanding of the nature or meaning of our everyday experiences.
- When winnowing themes, it is important to keep what is essential rather than incidental, the former making the phenomenon what it is and without which the phenomenon could not be what it is.

## Metasummary and metasynthesis
- Comprise systematic comparison of case studies to draw cross-case conclusions.
- They reduce the accounts while preserving the esnse of the account through the selection of key metaphors and orhanizers, such as themes, concepts, ideas and perspectives.
- It is the qualitative cousin of quantitative research's meta-analysis.
- Relies on a researcher's strategic collection and comparative analysis of themes that represent the essences and essentials of previous cases.
- It is not a method designed to produce oversimplification; rather, it is one in which differences are trained and complexity enlightened.
- The outcome will be more like a common understanding of the nature of a phenomenon, not a consensual worldview.

# Post-Coding Transitions
Outlines a few strategies for drawing greater meaning after first cycle coding:

- **Eclectic coding** is intended as a first draft or first cycle of coding with multiple methods simultaneously, followed by a revised draft during a second cycle with a more purposeful and select number of methods based on the impressions obtained the first time and following reflexive memo-writing.^[I think this is awkwardly situated in this book, and that it should have been treated as an overall coding strategy or workflow rather than as an interstitial method.]
- **Code mapping** seems similar to Clarke's [-@clarke2016] situational mapping and analysis, and involves iterative organization of codes:
  - **First iteration:** a simple list of all codes applied using a specific method
  - **Second iteration:** categorize the codes according to how they seem to go together, and assign names to the categories
  - **Third iteration:** categorize the categories, and assign names to them
  - **Fourth iteration:** refer to the coding method as a means of exploring how the major categories relate with each other, and perhaps even explain the phemomenon of interest
- **Code landscaping** is basically word clouds.
- **Operational model diagramming** can help disentangle the threads of our analysis.
- **Coding the codes** refers to lumping a series of codes into a common concept, with the aim of condensing the meanings of codes with more granular meanings.
- **Code charting** enables an analyst to scan and construct patterns from the codes, to develop initial assertions or propositions, and explore the possible dimensions which might be found in the range of codes.
  - Involves summarizing and classifying codes in a table, with axes possibly arranged along an ordinal scale.
  - Certain variables on the table can be considered more stable and fixed in one context and more dependent in another.
- **Tabletop categories** involves printing and physically arranging hard copies of codes and chunks of data on a tapletop, stapling them together, examining the thickness of stacks, and arranging them in different shapes (linear, circular, network, etc).
  - I imagine this could also be useful for accounting for codes "left behind" since there will be a physical trace of them that are not included in the physical arrangements.
- **From codes to theme**s refers to transforming the shorter terms that embody codes to longer-phrased themes, which may allow the analyst to draw out a code's truncated essence by eloborating on its meanings.
- **"Shop-talking" through the study** refers to talking with a trusted peer, colleague, advisor, mentor or friend about your research, and addressing any provocative questions they may pose.

# Second cycle coding methods


# References
