---
title: Situational analysis
description: Notes perpainting to situational analysis, which is a significant analytical framework that will support my research.
date: 2025-03-05
date-modified: last-modified
toc-depth: 6
toc-expand: 3
reference-location: document
categories: 
  - situational analysis
  - QDA methods
  - reading
---

Some notes on situational analysis and related methods are useful for my work.
Largely drawn from @clarke2016.

## Maps
The main strategies involved in SA are the three maps that researchers do across the full trajectory of the project, from the earliest design stages to the preparation of publications.

@clark2005 [: 30] explains why mapping is a useful method:

> Why situational maps?
> Why not narratives?
> There are a number of reasons.
> Let me start with some advantageous properties of maps elucidated by David Turnbull (2000) and elaborated by me.
> Because maps are visual representations, they helpfully rupture (some/most of) our normal ways of working and may provoke us to see things afresh (e.g., Latour 1986, 1988b; Suchman 1987).
> Maps also work more easily as discursive devices for mak ing assemblages and connections --- relational analyses.
> Maps are excellent "devices to materialize questions."
> Maps are tools of control, appropriation, and ideological expression.
> Mapping is a fundamental cognitive process we can "just do it."
> Mapping opens up knowledge spaces.
> Maps are great boundary objects --- devices for handling multiplicity, heterogeneity, and messiness in ways that can travel.
> Maps work well as spatial and temporal narratives.
> Maps allow unmapping and remapping.
> In addition, maps are very much part of the Chicago tradition as devices for analyzing relationality (see Chapter 2).
> Most important here, one can move around on/in maps much more quickly and easily than in narrative text, excellent for analytic work.
> Last, at least since the postcolonial era began, maps have been widely understood as very political --- and shifting --- devices.
> Hopefully, this will provoke enhanced reflexivity.
> The limitations of maps remain, of course, what can be "seen" by a particular analyst in a particular time and place.
> No method overcomes the situatedness of its users.
> A method can, however, attempt to use situatedness to improve the quality of the research.

### Situational maps
- From  @clarke2016 [: 13-14]
- Lay out _all_ the major human, non-human, discursive, historical, symbolic, cultural, political, and other elements in the research situation of concern.
- This map should ideally be made earlier on in the design phase.
- Lays out everything about which at least some data should be gathered.
- It meant to gain a sense of possibly important relations about all the elements.
- Also helps guide data collection and develop stronger funding proposals.^[I could also present this during my "turn" at the MCHI meeting in April, and solicit the other members' feedback.]
- Downstream in the research, situational maps are used to provoke analysis of relations among different elements through _relational mapping_.
- These maps capture and provoke discussion of the many and heterogeneous elements, their relationships to one another, and the messy complexities of the situation [@clarke2005: 83-103; @clarke2014; see also: @lather2007; @law1999; @law2004; @law2007; @law2006; @taylor2005].

- Clarke distinguishes between two kinds of situational maps:
  - Messy version
  - Ordered version

From @clarke2005 [: xxxv]:

> The first maps are the situational maps that lay out the major human, nonhuman, discursive, historical, symbolic, cultural, political, and other elements in the research situation of concern and provoke analy sis of relations among them.
> These maps are intended to capture and discuss the messy complexities of the situation in their dense relations and permuta tions. They intentionally work _against_ the usual simplifications so characteristic of scientific work (Star 1983, 1986) in particularly postmodern ways.

From @fosket2021: [: 272-273]:

> Mapping the Situation: Who/What Matters to STAR
> Upon entering the field of STAR, one of the first things I realized was that this "site" itself consisted of multiple sites.
> It comprised many different elements complexly organized and webbed together to form what I ultimately conceived of as the "STAR trial arena."
> Nonhuman actants (things of various kinds from furniture to technologies to discourses), social actors, body parts, research protocols, organi zations, and paperwork represent key elements in the constitution of the trial, and critical activists and passionate advocates are central.
> Additionally, the deeper I delved into the research, the more obvious and important the historical and political situatedness of STAR became.
> By requiring the researcher to map out all of the "analytically pertinent human and nonhuman, material and symbolic/dis cursive elements of a particular situation as framed by those in it _and by the analyst_" [@clarke2005: 87], situational maps draw out complexities and reveal which anticipated and unanticipated elements of the situation matter.

@clarke2016 [: 101]:

> Because they are intended to be done and redone multiple times across the life of a research project, there is no one “right” map.
> If you put something on it that turns out not to be important, you can delete it later or just ignore it.
> But if it was there in the first place, or got there during the research, at least you integrated it into the research design and sought some data about it systematically and have some sense of its relative importance.

#### Relational mapping
Framed as an extension of (messy) situational maps.
From @clarke2016 [: 107]:

> Once you have your messy map, you can do relational analyses.
> This is the next phase of analytic work to be done with the messy map.
> ...
> Then you take each element in turn and think about it in relation to each other element on the map.
> Literally center on one element and draw lines between it and the others and specify the nature of the relation ship by describing the nature of that line.
> One does this systematically, one at a time, from every element on the map to every other.
> Use as many maps as seem useful to diagram yourself through this analytic exercise.
> This to me is the major work one does with the situational map once it is constructed.
> This is one of those sites where being highly systematic in considering data can flip over into the exciting and creative moments of intellectual work.
> And sometimes there is no payoff.

With regards to sorting out and prioritizing the work at early stages, from @clarke2016 [: 108]:

> Relational maps also help the analyst to decide which stories—which relations—to pursue.
> This is especially helpful in the early stages of research when we tend to feel a bit mystified about where to go and what to memo.
> A session should produce several relational analyses with the situational maps and several memos.
> One would return to elaborate on these memos several times as data are collected.
> They should also be useful guides for theoretical sampling.

### Social worlds/aernas maps
- From @clarke2016 [: 14]
- Lay out all the _collective_ actors and the arena(s) of commitment within thich they are engaged in ongoing dicourses and negotiations.
- These maps offer _interpretations_ of the broader situation, taking up its social organizational, institutional and discursive dimensions [@strauss1978].
- They invoke distinctively poststructuralist assumptions:
  - we cannot assume directionalities of influence;
  - boundaries are open and porous;
  - negotiations are fluid;
  - discourses are multiple and potentially contradictory.
- _Negotiations_ of many kinds, from coercion to bargaining are the "basic social processes" that construct and constantly destabilize social worlds' relations and arenas maps.
- Symbolic interactionism tells is that things can always be otherwise --- not only individually, but also collectively, organizationally, institutionally, and discursively.
- These maps portray these poststructural possibilities.
- The flipside of social worlds/arenas maps are discourse/arenas maps.
- Social worlds are "universes of discourse". routinely producing discourses about themselves, about other social worlds, and about issues of concern in the arena.
- These discourses can be positionally mapped and analyzed.


From @clarke2005 [: xxxv-xxxvi]:

> Second, the social worlds/arenas maps lay out all of the _collective_ actors, key nonhuman elements, and the arena(s) of commitment within which they are engaged in ongoing discourse and negotiations.
> Such maps offer meso-level interpretations of the situation, explicitly taking up its social organizational, institutional, and discursive dimensions.
> They are distinctively postmodern irrtheir assumptions: We cannot assume directionalities of influence; bound aries are open and porous; negotiations are fluid; discourses are multiple and potentially contradictory.
> Negotiations of many kinds from coercion to bar gaining are the "basic social processes" that construct and constantly desta bilize the social worlds/arenas maps [@strauss1993].
> Things could always be otherwise-not only individually but also collectively/organizationally/ institutionally/discursively-and these maps portray such postmodern possibilities.

### Positional maps
- From @clarke2016 [: 14-15]
- Lay out the major positions taken and not taken in the data vis-a-vis particular axes of variation and difference, focus, and controversy found in the situation of concern.
- The discursive data can include interviews, observations, website, documents, etc.
- Most significantly, discursive maps are _not_ articulated with persons or groups but instead seek tp represent the full range of _discursive_ positions on key issues in the broad situation of concern.
- They allow multiple positions and contradictions to be articulated.
- Discourses are therefore disarticulated from their sites of production, decentering them and making analytic complexities more visible.

From @clark2005 [: xxxvi]:

> Third, positional maps lay out the major positions taken, and not taken, in the data vis-a-vis particular axes of variation and difference, focus, and controversy found in the situation of concern.
> Perhaps most significantly, positional maps are not articulated with persons or groups but rather seek to represent the full range of _discursive_ positions on particular issues --- fully allowing multiple positions and even contradictions within both individuals and collectivities to be articulated.
> Complexities are themselves heteroge neous, and we need improved means of representing them.

## Affinities with other frameworks
SA does not operate in a vacuum, and has some very strong productive relationships with other key theoretical and methodological frameworks emerging or radically evolving around the same time of its "birth".
Here I outline these affinities, articulate distinctions and similarities between them, and perhaps also identify certain antagonistic or opposing perspectives.

### Grounded Theory
- SA both relies on _and_ radically extends GT by pushing that method around the postmodern / postructuralist / interpretive turn and taking into account other theoretical and methodological developments since GT's origins in 1967 [@clarke2016: 77].
- Clarke framed SA in relation to GT as "the (re)turn to the social", or the reconfiguration of relationality taking place across the social sciences and humanities, specifically regarding the location of individual agency in participation as members of collectives engaged in universes of discourses.


### Actor-Network Theory
- See @clarke1987 and @clarke1992 for examples of SA work that draws from ANT (which was initially developed by @latour1986).


### Rhyzome Theory
- Situational maps are, in some way, representations of Deleuze and Guittari's [-@deleuze2007] concept of rhyzomes, a plant-based metaphor for multiple emergent shoots emerging from a plane with widespread horizontal, entwined networks of underground roots.
- Rhyzomes contrast and resist tree metaphors, which are vertical, have localized roots, and an original source like acorns or seeds.
- In contrast, rhyzomes invoke multiplicities of connections, relationality, linkages across people and non-human objects and beings, nomadic propagation, and growth.
- They are complex, contingent, and ultimately indeterminate --- messy!


### Poststructualist Feminism
- Key affinities include @haraway1991 and @lather2007.
- Clarke argues that GT has always been implicitly feminist (due to its pragmatic roots), and SA is one of a few attempts to draw that out more explicitly.
- SA shares with postructural feminism a criticsl lens through which one might identify biased outlooks in the research process.
- SA's emphasis on elucidating complexities and diversities of the elements and positions under examination also belie its usefulness as a tool for critical, feminist and anti-racist research [@clarke2016: 20-21].
- SA's consideration of non-human entities also lends itself to feminist critique and a social justice orientation in that it encourages identification of things and connections that exist and _that could exist but do not_ among various actors [@clarke2016: 21].
  - This draws on what @foucault1975 called the "conditions of possibility".
- Moreover, SA is inherently reflexive and strongly encourages researchers to acknowledge their positionality in relation to the things they are examining.
- It also encourages the researcher to situate themselves as the learner in critical inquiry, which can shift the tenor of the research in valuable ways.


### Participatory Action Research
- @genat2009 found it valuable to make social worlds/arenas maps of PAR projects themselves. carefully laying out and analyzing the worlds that should be involved, studied and analyzed.
- In this sense, SA is used as a reflexive method that articulates the interacting system of social worlds of specific stakeholders, which carry different commitments to their collective research initiative.
- Enables researchers and their local research partners to foreground _shared local understandings_ in order to both critique more dominant discourses originating elsewhere and to generate locally based statements of need on which policy positions to improve the local situation can be founded [@clarke2016: 17-18].

### Constructivism and Interpretivism
- Initiated by @blumer1954; @blumer1969, with roots in the pragmatic philosophy of George Herbert Mead^[As well as William James, Charles Sanders Pierce and John Dewey, but I think in highlighting Mead, Clarke intentionally situates symbolic interactism as a primarily _sociological_ framework --- which evolved as such at the University of Chicago in particular --- rather than as a more general philosophical orientation that exhibits a more rationalist form of logic in its east coast counterparts (at Harvard and Johns Hopkins, specifically).]
- One aspect of Blumer's position was that theory and method are inextricably entwined and nonfungible, which today would be described as co-constitutive of Star's [-@star1989] concept of "theory/methods packages" [@clarke2016: 26-27].
- See also Goffman's dismissal of scientistic claims of positivism in sociology by asserting that "a sort of sympathetic magic seems to be involved, the assumption being that if you go through the motions attributable to science then science will result. But it hasn't." [quoted in @vidich1994 [: 40]].
  - This corresponds with similar dismissals of positivism made by @geertz1973 and others.
- The next 20 years (ending during the early 1990s) constituted that @denzin1994 [: 9] called the era of blurred genres.
  - The first edition of the Handbook of Qualitative Research [@denzin1994] signalled loud and clear that the renaissance of qualitative research had arrived, after years of poignant, but scattered critiques of positivist modes of inquiry.

### Epistemic Cultures
- The concept of "epistemic cultures" (developed by @knorrcetina1999) asserts that through their actual practices of working, different scientific disciplines, specialties, and approaches generate distinctive cultures based on their epistemic assumptions, theories, and the practices used in doing such research.
- This concept is part of the "turn to practice" occurring throughout the social sciences and humanities.^[@clarke2016 does not mention them specifically, but @giddens1984 and @bourdieu1983 come to mind as relevant to the practice turn, too.].
- Epistemic cultures are one kind of social world.


### Social Interactionism

@clarke2021 [: 228] described a shift in Strauss' later work (while she was his student), which emphasized the conditional and situational aspects of action:

> He worked assiduously on framing and articulating ways to do grounded theory research that included specifying the structural conditions—seeking to literally make them vis ible in doing grounded theory analysis.
> Strauss's provisional solution, largely pur sued with Juliet Corbin, was the _conditional matrix_, a strategy for supplementing grounded theory's usual processual emphasis with serious attention to more struc tural contextual "_conditions_."
> Strauss's pragmatist interactionist sociology was based most of all in understanding _action as a situated activity_.
> Thus, for Strauss, the conditional matrix was a _situating device --- a heuristic means of enabling grounded theory researchers to envision the contexts and conditions under which the action is occurring_.

@clarke2021 [: 228-229] on Strauss' visual representation of "levels" of situational context:

> Here the concentric circles represent the more structural conditions _within_ which the focus of analysis dwells.
> Structural conditions are portrayed as _context_, arrayed _around_ the central action focus from local to global (from near the center/core to faraway places on the periphery).
> Action is in the center of the diagram —-- the grounded theory social process.
> ...
> In later versions of the conditional matrix [e.g., @strauss1988: 184], these conditions _spiral_ around the central focus of analysis, implying that such conditions may be closer in or more peripheral, adding a sense of fluidity and improving the diagram.

She [-@clarke2021: 230] goes on with a critique of this approach, which she then builds on:

> There are two problems here. First, the concentric circles seem to predetermine relations between particular concerns and the phenomenon under study.
> Second, the matrix gestures too abstractly toward the _possible salience of structural elements_ of situations rather than insisting on concrete and detailed _empirical specification of structural elements_ and their clear explication as requisite for thorough analysis.
> That is, _the relations among the important elements need to be empirically specified, studied, and interpreted_.
> In sum, to me, the conditional matrices ultimately did not do the conceptual analytic work Strauss and Corbin wanted to do in grounded theory method.
> My critiques ultimately provoked me to develop new strategies to better _focus empirically and analytically on the broader situation_.

Clarke's [-@clark2021: 231] describes the benefits of her alternative, the situational matrix:

> Here _the conditions **of** the situation are **in** the situation._
> _There is no such thing as "context,"_ and no concentric or spiraling circles.
> The conditional elements of the situation need to be specified in the analysis of the situation itself as _they are constitutive of it,_ not merely surrounding it or framing it or contributing to it.
> _They are it._
> Regardless of whether some actors might construe them as local or global, internal or external, close-in or far away, or whatever, the fundamental question is:
> "How do these conditions appear --— make themselves felt as consequential --- as integral parts of the empirical situation under examination?"
> At least some answers to that question can be found through doing situational mapping and analyses.

### Social Worlds/Arenas
From @clarke2005 [: xxix] on how Strauss' social worlds/arenas theory anticipated this emphasis on situations:

> Some years ago, Katovich and Reese (1993:400-405) interestingly argued that Strauss's negotiated order and related work recuperatively pulled the social around the postmodern turn through its methodological (grounded theoretical) recognition of the partial, tenuous, shifting, and unstable nature of the, empirical world and its constructedness.
> I strongly agree and would argue that Strauss also particularly furthered this "postmodernization of the social" through his conceptualizations of social worlds and arenas as modes of understanding the deeply situated yet always also fluid organizational ele ments of negotiations and discourses.
> He foreshadowed what later came to be known as postmodern assumptions: the instability of situations; the char acteristic changing, porous boundaries of both social worlds and arenas; social worlds seen as mutually constitutive/coproduced in the negotiations taking place in arenas; negotiations as central social processes hailing that "things can always be otherwise"; and so on.
> Negotiations also signal micropolitics of power and the powers of discourses-decentering the subject and power in its more fluid and discursive forms (e.g., Foucault 1979, 1980) --- as well as "the usual" meso/macro structural elements.

From @clarke2016 [: 89]:

> Social worlds theory assumes multiple collective actors—social worlds—in all kinds of negotiations in a broad and often contentious substantive arena.
> Arenas are focused on matters about which all the involved social worlds and actors care enough to be (1) committed to act, and (2) to produce discourses about arena concerns.
> Thus, arenas are sites of action and discourse.
> They are discursive sites in often complicated ways. Particular social worlds are constructed in other world's discourses as well as producing their own.
> But arenas usually endure for some time, and longstanding arenas are typically characterized by multiple, complex, and layered discourses that interpolate and combine old(er) and new(er) elements in on-going, contingent, and inflected practices.
> Further, because perspectives and commitments differ, arenas are usually sites of contestation and controversy.
> As such, they are especially good for analyzing heterogeneous perspectives or positions and for analyzing power in action (a lesson from technoscience studies) (e.g., Nelkin, 1995).
> Arenas are also especially amenable conceptual frames through which to work at a more meso/ organizational level, analyzing collective actors (social worlds), their work, and discourses in those arenas.

@clarke2005 [: 46] on what constitutes social worlds:

> Social worlds are universes of discourse (Mead 1938/1972:518) and principal affiliative mechanisms through which people organize social life.
> Insofar as it meaningfully exists, society as a whole, then, can be conceptualized as consisting of layered mosaics of social worlds and arenas.
> Strauss argued (1978:122) that each social world has at least one primary activity, particular sites, a technology (inherited or innovative means of carrying out the social world's activities), and, once under way, more formal organizations typically evolve to further one aspect or another of the world's activities.
> Hughes (1971) offered the more informal notion of a going con cern in which certain assumptions about what activities are important and what will be done can be taken for granted.
> People typically participate in a number of social worlds/going concerns simultaneously, and such par ticipation usually remains highly fluid.
> Entrepreneurs, deeply committed and active individuals (Becker 1963), cluster around the core of the world and mobilize those around them (Hughes 1971:54).
> Shibutani (1986:109) viewed social worlds as identity- and meaning-making segments in mass society, drawing on distinctive aspects of mass culture, with individuals capable of participation in only a limited number of such worlds.
> There can also be implicated actors in a social world and/or arena, actors silenced or only discursively present --- constructed by others for their own purposes (Clarke & Montini 1993).
> This concept provides a means of analyzing the situatedness of less powerful actors and the consequences of others' actions for them and raises issues of discursive constructions of actors and of nonhuman actants.
> I will therefore discuss it at some length. There are at least two kinds of implicated actors.
> First are those implicated actors who are physically present but are generally silenced/ignored/ invisibled by those in power in the social world or arena.
> Second are those implicated actors not physically present in a given social world but solely dis cursively constructed; they are conceived, represented, and perhaps targeted by the work of those others; hence they are discursively present.
> Neither category of implicated actors is actively involved in the actual negotiations of self-representation in the social world or arena, nor are their thoughts or opinions or identities explored or sought out by other actors through any openly empirical mode of inquiry (such as asking them questions).
> They are neither invited by those in greater power to participate nor to represent If themselves on their own terms. physically present, their perceptions are largely ignored and/or silenced.
> The difference between the two types turns on the issue of their physical presence.

@clarke2005 [: 47] on the presence of non-human actors in social worlds and their role in human experiences and conceptions:

> There can, of course, also be implicated actants-implicated nonhuman actors in situations of concern.
> Like humans, implicated actants can be physically and/or discursively present in the situation of inquiry.
> That is, human actors (individually and/or collectively as social worlds) routinely discursively construct nonhuman actants from those human actors' own perspectives.
> The analytic question here is: Who is discursively constructing what, and how and why are they doing so?

I think this is the main message, from @clarke2005 [: 48]

> The concept of implicated actors and actants can be particularly useful in the explicit analysis of power in social worlds and arenas.
> Such analyses are both complicated and enhanced by the fact that there are generally multiple discursive constructions circulating of both the human and nonhuman actors in any given situation.
> Analyzing power involves analyzing: Whose con structions of whom/what exist? Which are taken as "the real" constructions or the ones that "matter" in the situation by the various participants?
> Which are contested?
> Whose are ignored?
> By whom?
> Through understanding the discursive constructions of implicated actors and actants, analysts can grasp a lot about the social worlds and the arena in which they are active and some of the consequences of those actions for the less powerful.

From @clark22005 [: 55]:

> Strauss was similarly concerned with the invariably social/organizational ways in which what he frames as identities (rather than subjectivities) are produced and transformed throughout life through relations in social worlds in which people participate.
> ...
> Also traceable back to Mead, both Blumer and Strauss understood individuals as constituted through such collectivities, and collectivities as constituted through interaction with other collectivities.
> ...
> For Foucault, both individuals and collectivities are _constituted_ through discourses and disciplining.
> For Strauss, both individuals and collectivities are _produced_ through their participation in social worlds and arenas, including their discourses.
> While Foucault's language of disciplining and the constitution of subjectivity(ies) is more insistent and decenters "the knowing subject" much more thoroughly, these productions are accomplished through routine practices.
> Later in his career, when issues of agency concerned him more, @foucault1988 [: 11] (emphasis added) stated:
  > I would say that if now I am interested, in fact, in the way in which the subject constitutes himself in an active fashion, by the practices of self, these practices are nevertheless _not_ something that the individual invents by himself.
  > They are patterns that he finds in his culture and which are proposed, suggested and imposed on him by his culture, his society _and his social group_.
> This, to me, is a key point of articulation with Strauss-and with interac tionism more broadly.

### Discourse Studies
@clarke2016 [: 90] summary of Foucault's notion of discourse:

> Foucault (1972) began with the concept of "the order of discourse," asserting that ways of framing and representing linguistic conventions of meanings and habits of usage together constitute specific discursive fields or terrains.
> Conceptually, discourses are analytic modes of ordering the chaos of the world. His con cept of “discursive practices” described ways of being in the world that could, when historicized, be understood to produce distinctive “discursive forma tions” --— dominant discourses that bind together social injunctions about particular practices (Dreyfus & Rabinow, 1983, p. 59).
> Dominant discourses are reinforced through extant institutional systems of law, media, medicine, education, and so on —-- often operating in conjunction.
> A discourse is effected in disciplining practices, which produce subjects/subjectivities through surveillance, examination, and various technologies of the self --- ways of produc ing ourselves as properly disciplined subjects (e.g., Foucault, 1973, 1975, 1978, 1988).

### Non-Human Actors
@clarke2016 [: 92] on the importance of accounting for non-human actors:

> “Nonhuman actants” are not only present as nodes in the actor network in this approach, but also have agency.
> In science and technology studies, such conceptions exploded dualistic notions of a technical core and social superstructure—the separability of humans and machines. Instead, the social and technical together become a “seamless web,” co-constructed and mutually embedded (Bijker, Pinch, & Hughes, 1987; Latour, 1987).
> Woolgar (1991) captured this vividly in research on “how computers configure their users,” featuring the agency of the nonhuman in making us do things differ ently.
> With laptops or cell phones in place, we become “cyborgs” —-- cybernetic organisms (Haraway, [1985] 1991a).
> ...
> “Seeing” the agency of the nonhuman elements present in the situation disrupts the taken-for-granted, creating Meadian (e.g., [1927] 1964) moments of conceptual rupture through which we can see the world afresh.
> For example, “Magazines exist to sell readers to advertisers” ruptures the taken for- granted and offers a different perspective.
> The agency of magazines per se in the distribution of advertising discourses, normally invisible or at least not the lead point, is here rendered explicit and primary.

### Inversion

From @clarke2005 [: xxxvi-xxxvii]:

> @bowker1999 [: 10] discuss "infrastructural inversion" wherein the infrastructure of something is (unusually) revealed and even featured.
> ...
> Situational maps and analyses do a kind of "social inversion" in making the usually invisible and inchoate social fea tures of a situation more visible: all the key elements in the situation and their interrelations; the social worlds and arenas in which the phenomena of interest are embedded; the discursive positions taken and not taken by actors (human and nonhuman) on key issues; and the discourses themselves as constitutive of the situation.
> This is the postmodernization of a grounded theory grounded in symbolic interactionism and Foucaultian analytics.


### Boundary objects
From @clarke2005 [: 50-51]:

> Star and Griesemer (1989) developed the concept of boundary objects for things that exist at junctures where varied social worlds meet in an arena of mutual concern.
> Boundary objects can be treaties among countries, software programs for users in different settings, even concepts themselves.
> Here the basic social process is "translating the object" to address the multiple specific needs or demands placed upon it by the different worlds involved.
> Boundary objects are often very important to many/most of the worlds involved and hence can be sites of intense controversy and competition for the power to define them. For example, in Star and Griesemer's (1989) study of a regional zoology museum founded at the turn of the 20th century, the museum's spec imens were boundary objects.
> There were collections of multiple specimens of each species and subspecies, which, for the zoologists to find them useful, had to be very, very carefully tagged as to date and where collected, and very, verr carefully preserved and taxidermied.
> Aerial temperature, humidity, rainfall, and the precise habitat information on specimens were all important.
> The mammal and bird specimens were usually killed, gathered, and sent to the museum by amateur collectors and "mercenaries" (paid collectors) of varied backgrounds.
> Also involved were university administrators, a patron (herself an amateur collector), curators, research scientists, clerical staff, members of scientific clubs, and taxidermists.
> All had particular concerns about the spec imens that needed to be addressed and mutually articulated for the museum's collections to "work" well for all those involved.
> Thus the study of boundary objects can be an important pathway into often complicated situations, allowing the analyst to study the different participants through their distinc tiye relations with and discourses about the specific boundary object in question.
> This can help frame the broader situation of inquiry as well.
> Boundary objects can be human or nonhuman.

### Reform movements
From @clarke2005 [: 51] on movements and struggles _within_ social worlds:

> Based on Bucher's (1962, 1988; Bucher & Stelling 1977; Bucher & ,Strauss 1961) insights, interactionists have examined fluidity and change within social worlds and arenas by extending social movements analysis to include studies of reform movements of various kinds undertaken by segments or subworlds within professions, disciplines, and other work organi zations (Strauss et al. 1964, 1985/1997).
> Such reform movements can cut across whole arenas, such as rationalizing and standardizing hospital quality assurance in the late 20th century United States (Wiener 2000a, 2000b). Fujimura (1988, 1996), who studied the molecularization of biology, called such larger-scale processes "bandwagons."
> In many arenas, reform move ments have centered around processes of homogenization, standardization, formal classifications-things that would organize and articulate the work of the social worlds in that arena in parallel ways (e.g., Bowker & Star 1999; Clarke & Casper 1996; Timmermans & Berg 2003).

## Data Sources
From @clarke2021 [: 225]:

> The data for a situational analysis research project can be produced through in depth interviews and/or ethnographic observations, as is usual in grounded theory.
> However, situational analysis also strongly urges focusing on or also including extant discourse materials found in the situation under study as data—narrative, visual, and/or historical materials.
> These may include all kinds of documents, websites, imagery, material cultural objects, technological apparatuses, scientific or other specialized literatures, social media, and so forth.
> **In SA, whatever discursive materials exist in the situation of inquiry are viewed as constitutive of that situation—integral parts of it—and therefore worthy of analysis.**


From @clarke2005 [: xxii-xxiii]:

> Situational analysis supplements traditional or basic grounded theory with alternative approaches to _both_ data gathering and analysis/interpretation.
> In addition to producing and analyzing interview and ethnographic data, situational analysis promotes the analysis of extant narrative, visual, and his torical discourse materials.
> It enhances our capacities to do incisive studies of differences of perspective, of highly complex situations of action and position ality, of the heterogeneous discourses in which we are all constantly awash, and of the situated knowledges of life itself thereby produced.
> What I am ulti mately grappling toward are approaches that can simultaneously address voice and discourse, texts and the consequential materialities and symbolisms of the nonhuman, the dynamics of historical change, and, last but far from least, power in both its more solid and fluid forms.
> The outcomes of situational mappings should be "thick analyses" (Fosket 2002:40), paralleling Geertz's (1973) "thick descriptions."
> Thick analyses take explicitly into account the full array of elements in the situation and explicate their interrelations.

### Theoretical Sampling

From @clarke2005 [: xxxi-xxxii]:
> Unique to this approach has been, first, its requiring that analysis begin as soon as there are data.
> Coding begins immediately, and theorizing based on that coding does as well, however provisionally [@glaser1978].
> Second, "sampling" is driven not necessarily (or not only) by attempts to be "representative" of some social body or population or its heterogeneities but especially and explicitly by theoretical concerns that have emerged in the provisional analysis to date.
> Such "theoretical sampling" focuses on finding new data sources (persons or things-and not theories) that can best explic itly address specific theoretically interesting facets of the emergent analysis.
> Theoretical sampling has been integral to grounded theory from the outset, remains a fundamental strength of this analytic approach, and is crucial for situational analysis.
> In fact, "The true legacy of Glaser and Strauss is a collective awareness of the heuristic value of developmental research designs [through theoretical sampling] and exploratory data analytic strategies, not a 'system' for conducting and analyzing research" (Atkinson, Coffey, & Delamont 2003:162-163).

### Sensitizing Concepts
According to @clarke2005 [: 28] (emphasis original):

> ... a key aspect of the alternative approach developed here is focused on grounded theor_izing_ through the development of _sensitizing concepts_ and integrated analytics.

She goes on to quote @blumer1969 [:147-148]:

> [T]he concepts of our discipline are fundamentally sensitizing instruments.
> Hence, I call them "sensitizing concepts" and put them in contrast with definitive concepts
> ...
> A definitive concept refers precisely to what is common to a class of objects, and by the aid of a clear definition in terms of attributes or fixed bench marks
> ...
> A sensitizing concept lacks such specification
> ...
> Instead, it gives the user a general sense of reference and guidance in approaching empirical instances.
> Whereas definitive concepts provide prescriptions of what to see, **sensitizing concepts merely suggest directions along which to look**.

The bold part of this passage, which Clarke also emphasized, denotes recognition of the researcher's intervention.

## Situations
From @fosket2021: [: 269]:

> With her conceptualization of situational analyses, Clarke moved these theories further (2003, 2005).
> Here social worlds/arenas theory expands to include as consequential elements everything within a given situation.
> That is, it is not just the social worlds and their human and nonhuman elements that situate and shape knowledge and practices, but histories, discourses, symbols, institutions, material things, and anything else conceived of as present in the situation.

From @fosket2021: [: 270]:
> Within this framework, an understanding of the work of scientific knowl edge production requires an understanding of everything in the situation: the workplaces and their organizations, scientists and other workers, theories, mod els, research materials, instruments, technologies, skills and techniques, sponsor ship and its organization, regulatory groups, audiences, consumers, and so on. Each of the relevant elements is not merely contextual (i.e., background) but conditional. Each element is an integral aspect of the situation itself, constitutive of the practices and contingencies of the research work that constitutes the very construction of knowledge. Even those elements that are not physically present in the situation are part of the situation in a very real sense.

@clarke2005 [: 21-23] takes to heart four notions of "situations" while devising her methodology:

1. From @thomas1928, who argued that situations defined as real are real in their consequences. _Perspective_ dominates the interpretatiobs upon which actions are based. This is a very relational and ecological perspective.
2. From @mills1940, whose perspective is deeply pragmatist, in that he emphasized circumstances as important factors that influence action.
3. From @haraway1991, whose situated knowledges empasizes the embodied nature of all sensory experiences, and therefore of all knowledge.
4. From @massumi2002, who emphasized the situation of inquiry itself, and who draws a direct relationship with the researcher who enters a situation through its examination.
