---
title: Week notes (2025-W39)
date: 2025-09-26
date-modified: today
categories:
  - week notes
---

Overall, a very productive week.
Feels great to get back into the research after spending so much time in grant-land, and then suffering from a really terrible cold.
It's also the Jewish high holidays, which kinda scaffolds my work in a weirdly productive way.

I also received equipment that enables me to use both of my external displays, and settled on a combination digital and analog method for coding, so I'm finally getting into a more productive "zone".
I may write a blog post about that next week.

- Finished re-coding an entire interview.
  - Hand-coded and then brought into the qc database.
- Around halfway done hand-coding another interview.
- Got a primer on the state of the data tables for the cleaned-up email correspondence data.
- Initiated work on a protocol document for the CIHR Project Grant study.
- Attended David's seminar presentation.

- Revised proofs from a paper deriving from my dissertation work.
- Worked on a peer-review due this weekend.
