---
title: Week notes (2025-W06)
date: 2025-02-07
categories:
  - week notes
---

This week was a bit slower than usual.
The highlight was my meeting with Isabel to go over details about harmonization procedures and to discuss projects that may serve as potential cases.
I got a better sense of the community composition and the kinds of challenges that are commonly experienced, and Isabel was able to provide me with contacts to get in touch with once I'm ready to begin collecting data.

I was less active with regards to my methodology notes this week, having spent much time re-organizing and consolidating them.
I'm also reading about coding techniques and the foundational principles and debates surrounding grounded theory, but there is a lot of ground to cover and I'm taking it all in before I begin recording my thoughts in a systematic way.

I did some non-postdoc service this week too.
I started a peer-review that I had committed to, participated in the monthly [SSLA](https://sslarch.github.io/) meeting, and completed the first-pass screening of archaeology-related journals in the [Directory of Open Access Journals](https://doaj.org/) to verify their inclusion in [diamond.open-archaeo](https://diamond.open-archaeo.info/).
