---
title: Week notes (2025-W09)
date: 2025-02-28
categories:
  - week notes
---

This week I continued to work on my methodology notes, specifically going through the coding methods.
I also spent some time updating an article from my dissertation that was rejected from a journal again, and I'm trying to see how it can be published elsewhere (including as a preprint on my own website).

I experimented with the mechanism for keeping private data contained in a git submodule stored on a secure server, and fiddled with the quarto configuration too.
I updated the [tech specs blog post](../posts/tech-specs.qmd.qmd) with some notes.

I also started developing more comprehensive case files, outlining and reflecting on the first case and how I will approach it.

Being a bit ill this week, in combination with the paper rejection and another grant application, made it a bit of a slog.
It will be better next week, right?

On the bright side, I started a collaboration with one of Isabel's former students, trying to revive the momentum on an abandoned paper.
We really clicked and I foresee some good work coming out of this in the future, maybe even beyond this one initiaive.
