---
title: Week notes (2025-W05)
date: 2025-01-31
categories:
  - week notes
---
The first part of my week largely involved reading and taking notes on methodological texts.
I focused on case study design and qualitative coding techniques.
I plan to continue my methodology readings on coding techniques, memoing, interview methods and systematic note-taking, as well filling in gaps in my understanding of grounded theory and related debates.
These readings are especially useful in this planning stage, but also serve to fill time while I wait for my IRB approval.

On that note, I finally submitted my ethics application on Thursday.
I expect an expedited review based on the low-risk nature of the work.
I posted the materials I submitted on the [ethics protocol](../ethics-protocol.qmd) page.

I had my biweekly meeting with David, and he was very encouraging.

I met with Isabel Fortier again yesterday and we came up a list of six projects that may serve as potential cases.
We will discuss them in greater depth next week.

I finally sent some feedback on [qc](https://qualitative-coding.readthedocs.io/en/latest/).

Next week I also need to fulfill a few commitments not as related to the postdoc: I need to work on a peer-review I had committed to, continue assemmbling constructive feedback for qc, and continue [going through the DOAJ](https://github.com/open-archaeo/diamond.open-archaeo.info/issues/19) for the [diamond.open-archaeo](https://diamond.open-archaeo.info/) initiative.
